config/routes.rb
SuperSaml::Application.routes.draw do

  resources :fields

  root to: 'home#index'

  get 'saml/initialize', :to => 'saml#init'
  post 'saml/callback', :to => 'saml#consume'
  get 'saml/metadata', :to => 'saml#metadata'
  get 'saml/auth' => 'saml_idp#new'
  post 'saml/auth' => 'saml_idp#create'

end

app/models/field.rb
class Field < ActiveRecord::Base
  validates :name, :value,
    presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: [:show, :edit, :update, :destroy]

  # GET /fields
  def index
    @fields = Field.all
  end

  # GET /fields/1
  def show
  end

  # GET /fields/new
  def new
    @field = Field.new
  end

  # GET /fields/1/edit
  def edit
  end

  # POST /fields
  def create
    @field = Field.new(field_params)

    if @field.save
      redirect_to root_path, notice: 'Field was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /fields/1
  def update
    if @field.update(field_params)
      redirect_to root_path, notice: 'Field was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /fields/1
  def destroy
    @field.destroy
    redirect_to root_path, notice: 'Field was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field
      @field = Field.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def field_params
      params.require(:field).permit(:name, :value)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @fields = Field.all
  end
end

app/controllers/saml_controller.rb
require 'ruby-saml'
class SamlController < ApplicationController

  def init
    request = OneLogin::RubySaml::Authrequest.new
    if params[:consumer_service_url].present?
      redirect_to(request.create(saml_settings))
    else
      redirect_to(root_path, alert: 'Consumer Service URL is required!')
    end
  end

  def metadata
    meta = OneLogin::RubySaml::Metadata.new
    render xml: meta.generate(saml_settings)
  end

  private

  def saml_settings
    settings = OneLogin::RubySaml::Settings.new
    settings.assertion_consumer_service_url = params[:consumer_service_url]
    settings.issuer = params[:consumer_service_url]
    settings.idp_sso_target_url = "#{host_with_port}/saml/auth"
    settings.idp_cert_fingerprint = SamlIdp::Default::FINGERPRINT
    settings.name_identifier_format = "urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified"
    settings
  end

  def host_with_port
    str = "#{request.protocol}#{request.host}"
    str << ':3001' if Rails.env.development?
    str
  end
end

app/controllers/saml_idp_controller.rb
class SamlIdpController < SamlIdp::IdpController

  layout 'application'

  def new
    @fields = Field.all
  end

  def idp_make_saml_response
    encode_response
  end

  def custom_attributes
    ''.tap do |str|
      params[:attributes].each do |key, val|
        str << %[<Attribute Name="#{key}" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"><AttributeValue>#{val}</AttributeValue></Attribute>]
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_form.html.erb
<%= form_for(@field) do |f| %>
  <% if @field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@field.errors.count, "error") %> prohibited this field from being saved:</h2>

      <ul>
      <% @field.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fields/edit.html.erb
<h1>Editing field</h1>

<%= render 'form' %>

<%= link_to 'Show', @field %> |
<%= link_to 'Back', fields_path %>

app/views/fields/index.html.erb
<%= link_to('Back home', root_path) %>

<h1>Listing fields</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @fields.each do |field| %>
    <tr>
      <td><%= field.name %></td>
      <td><%= field.value %></td>
      <td><%= link_to 'Show', field %></td>
      <td><%= link_to 'Edit', edit_field_path(field) %></td>
      <td><%= link_to 'Destroy', field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Field', new_field_path %>

app/views/fields/new.html.erb
<h1>New field</h1>

<%= render 'form' %>

<%= link_to 'Back', fields_path %>

app/views/fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @field.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @field.value %>
</p>

<%= link_to 'Edit', edit_field_path(@field) %> |
<%= link_to 'Back', fields_path %>

app/views/home/index.html.erb
<h1>Welcome to Super SAML</h1>

<div>
  <% if @fields.any? %>
    <h3>Your list of fields | <%= link_to('new field', new_field_path) %></h3>
    <hr/>
    <table>
      <thead>
      <tr>
        <th>Name</th>
        <th>Value</th>
        <th></th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% @fields.each do |field| %>
        <tr>
          <td><%= field.name %></td>
          <td><%= field.value %></td>
          <td><%= link_to 'Edit', edit_field_path(field) %></td>
          <td><%= link_to 'Destroy', field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <div>
      You have no fields! Ahhhh!! Better add some <%= link_to('tasty fields', new_field_path) %>
    </div>
  <% end %>
</div>
<div style="padding: 10px 0">
  <hr/>
</div>
<% if request.flash.any? %>
  <div id="error_explanation" style="padding-bottom: 10px">
    <%= request.flash.discard.collect { |_, v| v }.first %>
  </div>
<% end %>
<h4>New SAML Request</h4>
<div>
  <%= form_tag(saml_initialize_path, method: :get) do %>
    <p><%= label_tag(:consumer_service_url, 'Where are sending this request?') %> (required)</p>

    <p><%= text_field_tag(:consumer_service_url) %></p>

    <p><%= submit_tag('New SAML Request') %></p>

  <% end %>
</div>

<script type="text/javascript">
  document.getElementById('consumer_service_url').focus();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuperSaml</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/saml_idp/new.html.erb
<h3>The fingerprint of the X509 Certificate</h3>
<div>
  <b><%= SamlIdp::Default::FINGERPRINT %></b>
</div>
<%= form_tag do %>
  <%= hidden_field_tag("SAMLRequest", params[:SAMLRequest]) %>
  <% if @fields.any? %>
    <% @fields.each do |field| %>
      <p><%= label_tag("attributes[#{field.name}]", field.name.titleize) %></p>
      <p><%= text_field_tag("attributes[#{field.name}]", field.value) %></p>
    <% end %>
  <% else %>
    <p><b>Ahhhh! You don't have any fields</b></p>
  <% end %>
  <p>
    <%= submit_tag "Create SAML Request" %>
    or
    <%= link_to('Go back', root_path) %>
  </p>
<% end %>